# Generated by Django 5.2.7 on 2025-12-04 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80)),
                ('detalle', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=60)),
                ('cantDisponible', models.IntegerField()),
                ('unidad', models.CharField(blank=True, max_length=20, null=True)),
                ('marca', models.CharField(blank=True, max_length=60, null=True)),
                ('color', models.CharField(blank=True, max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('descripcion', models.TextField()),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='productos')),
                ('es_destacado', models.BooleanField(default=False)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='appTienda.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('contacto', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('plataforma', models.CharField(choices=[('fb', 'Facebook'), ('ig', 'Instagram'), ('wa', 'WhatsApp'), ('local', 'Presencial'), ('web', 'Sitio web'), ('otro', 'Otro')], default='web', max_length=20)),
                ('fecha_solicitada', models.DateField(blank=True, null=True)),
                ('estado_pedido', models.CharField(choices=[('solicitado', 'Solicitado'), ('aprobado', 'Aprobado'), ('proceso', 'En proceso'), ('realizada', 'Realizada'), ('entregada', 'Entregada'), ('finalizada', 'Finalizada'), ('cancelada', 'Cancelada')], default='solicitado', max_length=20)),
                ('estado_pago', models.CharField(choices=[('pendiente', 'Pendiente'), ('parcial', 'Parcial'), ('pagado', 'Pagado')], default='pendiente', max_length=20)),
                ('token_seguimiento', models.CharField(blank=True, max_length=20, unique=True)),
                ('foto_ref1', models.ImageField(blank=True, null=True, upload_to='pedidos')),
                ('foto_ref2', models.ImageField(blank=True, null=True, upload_to='pedidos')),
                ('producto_referencia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='appTienda.producto')),
            ],
        ),
    ]
